name = "CudaRBMs"
uuid = "4e7460e3-fd1b-4f88-90fa-49c1b80b3e77"
authors = ["Jorge Fernandez-de-Cossio-Diaz <j.cossio.diaz@gmail.com>"]
version = "1.0.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
RestrictedBoltzmannMachines = "12e6b396-7db5-4506-8cb6-664a4fe1e50e"

[compat]
CUDA = "3"
RestrictedBoltzmannMachines = "0.38, 0.39, 1, 2"
julia = "1.8"
Adapt = "3"